### ISSUE TITLE
Tracking issue - doc structure

### ISSUE THREAD

**Issue by zmitchell** [NixOS/nix.dev#492]
This is a tracking issue for determining and implementing the documentation structure

## Steps
- [x] Create a PR for feedback on structure
    - PR: https://github.com/NixOS/nix.dev/pull/495
- [ ] Present the doc structure at a documentation team meeting for approval
- [ ] Create a PR updating the site structure to match the agreed upon doc structure (PR: WIP)

**Comment by zmitchell** [comment]
Based on feedback and discussions, it sounds like deciding on the documentation structure before writing any documentation is putting the cart before the horse. A smaller, more tractable problem is to first organize `nix.dev` around the documentation categories as seen in https://github.com/NixOS/nix.dev/issues/499
