### ISSUE TITLE
Updates of NixOS Testing library

### ISSUE THREAD

**Issue by olafklingt** [NixOS/nix.dev#727]
## Project description
The aim is to improve the documentationof the NixOS Testing Library.
This includes tasks on nixos.wiki nix.dev NixOS and Nixpkgs manual.

## Steps
- [ ] clarify the role of new functions in the new/current interface
  - [ ] add clarification to Nixpkgs manual
  - [ ] adopt new interface on nix.dev
  - [ ] adopt new interface on nixos.wiki
- [ ] review NixOS manual
  - [ ] find position for NixOS tests that do not aim to be part of NixOS tests themselves (not NixOS tests, but test by NixOS users)
- [ ] consider Test receips (and their position)
