### ISSUE TITLE
Guides and Recipes overview

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix.dev#908]
This tracking issue is to keep an overview of guides for most common use cases.

- [ ] Dependency management with `npins` (with Home Manager)
- [ ] Automatic environments with `direnv` (with Home Manager)
- [ ] Package scaffolding (with [`nix-init`](https://github.com/nix-community/nix-init))
- [ ] Building a bootable NixOS ISO image
- [ ] Running pre-built binaries on NixOS
- [ ] https://github.com/NixOS/nix.dev/issues/463
- [ ] https://github.com/NixOS/nix.dev/issues/490
- [ ] Managing secrets (no optimal solution)
- [ ] https://github.com/NixOS/nix.dev/issues/907 (no optimal solution)

**Comment by malteneuss** [comment]
Would the following topics make sense as well here?
- remote builders. I cleaned up https://wiki.nixos.org/wiki/Distributed_build but it would benefit from another round of compressing the content and become official.
- Cross-compiling NixosConfigurations. Give some guidance which style of https://discourse.nixos.org/t/recommended-style-to-cross-compile-flake-nixossystems/45305/2 is recommended when. Maybe even offer an alternative explanation to the NixOS manual.
- NixOS tests.  How to write and execute them.

**Comment by fricklerhandwerk** [comment]
@malteneuss absolutely!

I currently have the distributed build scenario at the top of my mind, recently updated the Nix manual on the topic, and would gladly review contributions.

Updating the cross compilation article with something that actually works would also be great.

**Comment by vuongpd95** [comment]
I have the recent know-how of a full LSP with neovim setup on NixOS 25.05 (with home-manager) without using any neovim package manager (e.g. Vim Plug) or language server binaries manager (e.g. Mason) since they go against NixOS design.

I have faced a lot of difficulties setting everything up but managed to do it in the end. The developer experience is on par with my other system running Ubuntu.

I think it can be helpful for other people but not sure if nix.dev recipes is the right place to host it.

The setup:
- is a single configuration.nix file with inline home-manager neovim extraLuaConfig. It's not broken into multiple files so it's very easy to follow.
- has home-manager wezterm basic configurations inline as well.
- neovim LSP setup with lsp-config and auto-completion setup.
- demo setup for multiple popular language servers (Taliwindcss, Svelte, Vue, TS, PHP, Nix, Bash, Lua, Ruby, Godot) with their own gotchas.

I can break the above setup into multiple recipes.

**Comment by fricklerhandwerk** [comment]
@vuongpd95 that sounds quite awesome! For the sake of usability and reviewability it would be ideal to add small independent chunks that build on top of each other and lead to what you're describing. Because cleanly setting up home manager is valuable independent of the editor, and so is adding libraries to the module evaluation. And then if using  [nixvim](https://github.com/nix-community/nixvim) there should be very little left to do because the details are maintained there. All the tutorial or guide would need to do is pick one (in principle arbitrary) end-to-end story and refer to reference documentation from there.

Ideally of course we would also have a collection of useful examples, but the infrastructure and and contributor documentation for making sure they work as intended isn't in place yet. (There's something in the works at https://ngi.nixos.org but it's not ready to be replicated yet.) So I'd consider that a stretch goal.

Getting any small thing in the direction of the outline merged would be really really good already.
